### ISSUE TITLE
Updated nvimux

### ISSUE THREAD

**Issue by hkupty** [nathanaelkane/dotfiles#1]
Hi, sorry for dropping in here like this, but I found your `nvimux.vim` quite interesting and made a change that might help you.

Now, instead of defining the blocks of remap, you can define a list of nvimux remappings:

``` vim
" So instead of 
nnoremap <C-g>, :call RenameTab()<CR>
vnoremap <C-g>, :call RenameTab()<CR>
inoremap <C-g>, <ESC>:call RenameTab()<CR>
tnoremap <C-g>, <C-\><C-n>:call RenameTab()<CR>

" ... and the others

" You can now
let g:nvimux_custom_bindings = [
  \[',', ':call RenameTab()<CR>, ['n', 'v', 'i', 't']],
  \['<C-g>', ':call LastActiveTab()<CR>', ['n', 'v', 'i', 't']],
  \['m', ':call MoveTab()<CR>', ['n', 'v', 'i', 't']]
\]
```

Once again, sorry for sneaking into your config, but you inspired me to add this feature!

**Comment by nathanaelkane** [comment]
Cool, thanks for letting me know. I was going to create an issue on the nvimux repo at some point to request a feature just like that :)
